### ISSUE TITLE
Pricing tier needs to be consistent in text and images

### ISSUE THREAD

**Issue by indcoder** [GlobalAICommunity/Workshop-CustomVisionAITools#3]
While the text instructs explicitly to use S0 pricing tier throughout the workshop but under the Build classifier the images show F0 as the pricing tier of the resource group.

![image](https://user-images.githubusercontent.com/2099300/70546328-16834480-1b95-11ea-9df8-b6cb49f260fa.png)

**Comment by mdragt** [comment]
Thanks for letting us know! It has been changed now.
